name: Python Application Workflow

on:
  push:
    branches: [main]
    paths-ignore:  # 避免循环触发 ▼
      - 'result/**'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的权限
    env:
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv python-dotenv openai PyPDF2 requests

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "128622896@qq.com"
          git config --global user.name "ZerooVector"
          git add .
          git commit -m "Auto commit: update files [skip ci]" || echo "No changes to commit"
          git pull --rebase
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
